DROP table IF EXISTS user_info CASCADE;
DROP table IF EXISTS users CASCADE;
DROP table IF EXISTS tasks CASCADE;
DROP table IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS user_info
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    roles    VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled      boolean DEFAULT true NOT NULL,
    first_name   varchar(250),
    last_name    varchar(250),
    phone        varchar(250),
    user_info_id BIGINT,
    CONSTRAINT fk_users FOREIGN KEY (user_info_id) REFERENCES user_info (id)
);

CREATE TABLE IF NOT EXISTS tasks
(
    task_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        varchar(100) NOT NULL,
    description  varchar(2000) NOT NULL,
    status       varchar(100) NOT NULL,
    priority     varchar(100) NOT NULL,
    author_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    performer_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       varchar(500) NOT NULL,
    author_id  BIGINT REFERENCES users (user_id) ON DELETE CASCADE NOT NULL,
    task_id    BIGINT REFERENCES tasks (task_id) ON DELETE CASCADE NOT NULL,
    created    TIMESTAMP WITHOUT TIME ZONE
);